// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOBiCZ-to7VVio7CAntqwIRfPIhiZgKZg',
    appId: '1:1042612043664:web:ae2ba268e28fdfb367fd15',
    messagingSenderId: '1042612043664',
    projectId: 'notely-7fcda',
    authDomain: 'notely-7fcda.firebaseapp.com',
    storageBucket: 'notely-7fcda.firebasestorage.app',
    measurementId: 'G-MENF8EKM0Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6NLZbDbmijSlv12cil2ayxPPTrC31oWg',
    appId: '1:1042612043664:android:280418f3d2fce5cf67fd15',
    messagingSenderId: '1042612043664',
    projectId: 'notely-7fcda',
    storageBucket: 'notely-7fcda.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCruzVCUUn-T5K-2J0O1hAfSrQCIpb00Rg',
    appId: '1:1042612043664:ios:5638b67c4ecc614667fd15',
    messagingSenderId: '1042612043664',
    projectId: 'notely-7fcda',
    storageBucket: 'notely-7fcda.firebasestorage.app',
    iosBundleId: 'com.example.flutterCourse2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCruzVCUUn-T5K-2J0O1hAfSrQCIpb00Rg',
    appId: '1:1042612043664:ios:5638b67c4ecc614667fd15',
    messagingSenderId: '1042612043664',
    projectId: 'notely-7fcda',
    storageBucket: 'notely-7fcda.firebasestorage.app',
    iosBundleId: 'com.example.flutterCourse2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOBiCZ-to7VVio7CAntqwIRfPIhiZgKZg',
    appId: '1:1042612043664:web:decfdf96cd8baa0a67fd15',
    messagingSenderId: '1042612043664',
    projectId: 'notely-7fcda',
    authDomain: 'notely-7fcda.firebaseapp.com',
    storageBucket: 'notely-7fcda.firebasestorage.app',
    measurementId: 'G-MSVVG6GPWK',
  );
}
