// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_course_2/test/page/create_update_note_view_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flutter_course_2/repositories/note_repository.dart' as _i3;
import 'package:flutter_course_2/services/auth/auth_provider.dart' as _i5;
import 'package:flutter_course_2/services/auth/auth_user.dart' as _i6;
import 'package:flutter_course_2/services/crud/note_services.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDatabaseNote_0 extends _i1.SmartFake implements _i2.DatabaseNote {
  _FakeDatabaseNote_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [NoteRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockNoteRepository extends _i1.Mock implements _i3.NoteRepository {
  MockNoteRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.DatabaseNote> createNote({required _i2.DatabaseUser? owner}) =>
      (super.noSuchMethod(
            Invocation.method(#createNote, [], {#owner: owner}),
            returnValue: _i4.Future<_i2.DatabaseNote>.value(
              _FakeDatabaseNote_0(
                this,
                Invocation.method(#createNote, [], {#owner: owner}),
              ),
            ),
          )
          as _i4.Future<_i2.DatabaseNote>);

  @override
  _i4.Future<_i2.DatabaseNote> updateNote({
    required _i2.DatabaseNote? note,
    required String? text,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateNote, [], {#note: note, #text: text}),
            returnValue: _i4.Future<_i2.DatabaseNote>.value(
              _FakeDatabaseNote_0(
                this,
                Invocation.method(#updateNote, [], {#note: note, #text: text}),
              ),
            ),
          )
          as _i4.Future<_i2.DatabaseNote>);

  @override
  _i4.Future<void> deleteNote({required int? id}) =>
      (super.noSuchMethod(
            Invocation.method(#deleteNote, [], {#id: id}),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<Iterable<_i2.DatabaseNote>> getNotes({
    required _i2.DatabaseUser? owner,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getNotes, [], {#owner: owner}),
            returnValue: _i4.Future<Iterable<_i2.DatabaseNote>>.value(
              <_i2.DatabaseNote>[],
            ),
          )
          as _i4.Future<Iterable<_i2.DatabaseNote>>);
}

/// A class which mocks [AuthProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthProvider extends _i1.Mock implements _i5.AuthProvider {
  MockAuthProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i6.AuthUser?> logIn({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logIn, [], {#email: email, #password: password}),
            returnValue: _i4.Future<_i6.AuthUser?>.value(),
          )
          as _i4.Future<_i6.AuthUser?>);

  @override
  _i4.Future<_i6.AuthUser?> createUser({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createUser, [], {
              #email: email,
              #password: password,
            }),
            returnValue: _i4.Future<_i6.AuthUser?>.value(),
          )
          as _i4.Future<_i6.AuthUser?>);

  @override
  _i4.Future<void> logOut() =>
      (super.noSuchMethod(
            Invocation.method(#logOut, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> sendEmailVerification() =>
      (super.noSuchMethod(
            Invocation.method(#sendEmailVerification, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> sendPasswordReset({required String? toEmail}) =>
      (super.noSuchMethod(
            Invocation.method(#sendPasswordReset, [], {#toEmail: toEmail}),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
