// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPnwrmKhyAL2fSFOxEYG0XMYaOXTzyUko',
    appId: '1:731227938877:web:72a0df86d4a777c10aca54',
    messagingSenderId: '731227938877',
    projectId: 'fluttercourse-195e9',
    authDomain: 'fluttercourse-195e9.firebaseapp.com',
    storageBucket: 'fluttercourse-195e9.firebasestorage.app',
    measurementId: 'G-1TP4Q5Y3DN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBERItEjQfu8wBJl0veZ9oLuD0JQd3pvVU',
    appId: '1:731227938877:android:daef03aa818cfc770aca54',
    messagingSenderId: '731227938877',
    projectId: 'fluttercourse-195e9',
    storageBucket: 'fluttercourse-195e9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEfJ69k0jcqUvXzMk6YGhg4jj4FFH_8CE',
    appId: '1:731227938877:ios:ed84b7d8176fbdbc0aca54',
    messagingSenderId: '731227938877',
    projectId: 'fluttercourse-195e9',
    storageBucket: 'fluttercourse-195e9.firebasestorage.app',
    iosBundleId: 'com.example.flutterCourse2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEfJ69k0jcqUvXzMk6YGhg4jj4FFH_8CE',
    appId: '1:731227938877:ios:ed84b7d8176fbdbc0aca54',
    messagingSenderId: '731227938877',
    projectId: 'fluttercourse-195e9',
    storageBucket: 'fluttercourse-195e9.firebasestorage.app',
    iosBundleId: 'com.example.flutterCourse2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPnwrmKhyAL2fSFOxEYG0XMYaOXTzyUko',
    appId: '1:731227938877:web:d8f4929b5b128d8a0aca54',
    messagingSenderId: '731227938877',
    projectId: 'fluttercourse-195e9',
    authDomain: 'fluttercourse-195e9.firebaseapp.com',
    storageBucket: 'fluttercourse-195e9.firebasestorage.app',
    measurementId: 'G-YGZ64ME4QJ',
  );

}