// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_course_2/test/repositories/note_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flutter_course_2/services/crud/note_services.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDatabaseUser_0 extends _i1.SmartFake implements _i2.DatabaseUser {
  _FakeDatabaseUser_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDatabaseNote_1 extends _i1.SmartFake implements _i2.DatabaseNote {
  _FakeDatabaseNote_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [NotesService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotesService extends _i1.Mock implements _i2.NotesService {
  MockNotesService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<List<_i2.DatabaseNote>> get allNotes =>
      (super.noSuchMethod(
            Invocation.getter(#allNotes),
            returnValue: _i3.Stream<List<_i2.DatabaseNote>>.empty(),
          )
          as _i3.Stream<List<_i2.DatabaseNote>>);

  @override
  _i3.Future<_i2.DatabaseUser> getOrCreateUser({
    required String? email,
    bool? setAsCurrentUser = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getOrCreateUser, [], {
              #email: email,
              #setAsCurrentUser: setAsCurrentUser,
            }),
            returnValue: _i3.Future<_i2.DatabaseUser>.value(
              _FakeDatabaseUser_0(
                this,
                Invocation.method(#getOrCreateUser, [], {
                  #email: email,
                  #setAsCurrentUser: setAsCurrentUser,
                }),
              ),
            ),
          )
          as _i3.Future<_i2.DatabaseUser>);

  @override
  _i3.Future<_i2.DatabaseNote> updateNote({
    required _i2.DatabaseNote? note,
    required String? text,
    int? syncStatus,
    String? remoteId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateNote, [], {
              #note: note,
              #text: text,
              #syncStatus: syncStatus,
              #remoteId: remoteId,
            }),
            returnValue: _i3.Future<_i2.DatabaseNote>.value(
              _FakeDatabaseNote_1(
                this,
                Invocation.method(#updateNote, [], {
                  #note: note,
                  #text: text,
                  #syncStatus: syncStatus,
                  #remoteId: remoteId,
                }),
              ),
            ),
          )
          as _i3.Future<_i2.DatabaseNote>);

  @override
  _i3.Future<Iterable<_i2.DatabaseNote>> getAllNotes() =>
      (super.noSuchMethod(
            Invocation.method(#getAllNotes, []),
            returnValue: _i3.Future<Iterable<_i2.DatabaseNote>>.value(
              <_i2.DatabaseNote>[],
            ),
          )
          as _i3.Future<Iterable<_i2.DatabaseNote>>);

  @override
  _i3.Future<Iterable<_i2.DatabaseNote>> getAllNotesForSync() =>
      (super.noSuchMethod(
            Invocation.method(#getAllNotesForSync, []),
            returnValue: _i3.Future<Iterable<_i2.DatabaseNote>>.value(
              <_i2.DatabaseNote>[],
            ),
          )
          as _i3.Future<Iterable<_i2.DatabaseNote>>);

  @override
  _i3.Future<_i2.DatabaseNote> getNote({required int? id}) =>
      (super.noSuchMethod(
            Invocation.method(#getNote, [], {#id: id}),
            returnValue: _i3.Future<_i2.DatabaseNote>.value(
              _FakeDatabaseNote_1(
                this,
                Invocation.method(#getNote, [], {#id: id}),
              ),
            ),
          )
          as _i3.Future<_i2.DatabaseNote>);

  @override
  _i3.Future<int> deleteAllNotes() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAllNotes, []),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<void> deleteNote({required int? id}) =>
      (super.noSuchMethod(
            Invocation.method(#deleteNote, [], {#id: id}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> hardDeleteNote({required int? id}) =>
      (super.noSuchMethod(
            Invocation.method(#hardDeleteNote, [], {#id: id}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i2.DatabaseNote> createNote({required _i2.DatabaseUser? owner}) =>
      (super.noSuchMethod(
            Invocation.method(#createNote, [], {#owner: owner}),
            returnValue: _i3.Future<_i2.DatabaseNote>.value(
              _FakeDatabaseNote_1(
                this,
                Invocation.method(#createNote, [], {#owner: owner}),
              ),
            ),
          )
          as _i3.Future<_i2.DatabaseNote>);

  @override
  _i3.Future<void> updateNoteSyncStatus({
    required int? id,
    required int? status,
    String? remoteId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateNoteSyncStatus, [], {
              #id: id,
              #status: status,
              #remoteId: remoteId,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i2.DatabaseUser> getUser({required String? email}) =>
      (super.noSuchMethod(
            Invocation.method(#getUser, [], {#email: email}),
            returnValue: _i3.Future<_i2.DatabaseUser>.value(
              _FakeDatabaseUser_0(
                this,
                Invocation.method(#getUser, [], {#email: email}),
              ),
            ),
          )
          as _i3.Future<_i2.DatabaseUser>);

  @override
  _i3.Future<_i2.DatabaseUser> createUser({required String? email}) =>
      (super.noSuchMethod(
            Invocation.method(#createUser, [], {#email: email}),
            returnValue: _i3.Future<_i2.DatabaseUser>.value(
              _FakeDatabaseUser_0(
                this,
                Invocation.method(#createUser, [], {#email: email}),
              ),
            ),
          )
          as _i3.Future<_i2.DatabaseUser>);

  @override
  _i3.Future<void> deleteUser({required String? email}) =>
      (super.noSuchMethod(
            Invocation.method(#deleteUser, [], {#email: email}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> open() =>
      (super.noSuchMethod(
            Invocation.method(#open, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
